DEFAULT_CONFIG = {
    "preset_name": "Cartel principal",
    "message": "🔥 Bienvenidos a Kamasys 🚀",
    "style": "neon",
    "animation_mode": "marquee",
    "direction": "left",
    "font_family": "orbitron",
    "font_size": 120,
    "speed": 18,
    "text_color": "#ffd166",
    "background_color": "#050505",
    "accent_color": "#ff7b00",
    "glow": 70,
    "brightness": 100,
    "letter_spacing": 6,
    "padding_x": 48,
    "padding_y": 20,
    "border_radius": 18,
    "border_width": 0,
    "uppercase": False,
    "blink": False,
    "outline": False,
    "shadow_enabled": True,
    "show_background_grid": True,
    "container_opacity": 100,
}
