DEFAULT_CONFIG = {
    "preset_name": "Cartel principal",
    "message": "🔥 BIENVENIDOS|⚡ KAMASYS|🚀 TECH",
    "style": "literal_led",
    "animation_mode": "marquee",
    "direction": "left",
    "font_family": "orbitron",
    "font_size": 120,
    "speed": 18,
    "text_color": "#ff2222",
    "background_color": "#050505",
    "accent_color": "#ff8800",
    "glow": 80,
    "brightness": 100,
    "letter_spacing": 8,
    "padding_x": 48,
    "padding_y": 20,
    "border_radius": 12,
    "border_width": 0,
    "uppercase": True,
    "blink": False,
    "outline": False,
    "shadow_enabled": True,
    "show_background_grid": True,
    "container_opacity": 100,
    "multi_color": True,
    "led_border_dots": True,
    "text_effect": "none",
}
